### PR TITLE
Add GitHub Actions CI

### PR DESCRIPTION
**Pull request by bshapiroalbert**
Attempting to add GitHub Actions CI to transition away from Travis CI.

### CODE REVIEW

**Comment by Hazboun6** [comment]
@bshapiroalbert I assume that this is integrated in GitHub, in a way that it should be showing on the PR page? I.e., can you tell that the tests are running on Actions?

**Comment by bshapiroalbert** [comment]
@Hazboun6 yes, it should show up. I have it showing up (currently failing) on my local repo (https://github.com/bshapiroalbert/PsrSigSim/pull/22), but I had not other CI set up there. Gonna work on figuring that out.

**Comment by Hazboun6** [comment]
Interesting. You can delete the `.travis.yml` and maybe that'll make it start in the `PsrSigSim` PR.

**Comment by bshapiroalbert** [comment]
@Hazboun6 , based on what it says here: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories , I think we might have to just add the workflows .yml to this base repo to get it to run. I can easily add that if you want. Though as you mentioned somewhere else, there is still an issue with the 3.6 test.

**Comment by bshapiroalbert** [comment]
This is working and passing all tests in my branch locally, so I'm going to merge it here. Hopefully will not break anything and will allow us to run GitHub Actions CI tests.

**Pull request merged**
