### PR TITLE
template functions handle voltage & intensity data

### LINKED ISSUE #25: User specified profiles are never transformed from intensity to voltage
## primary issue
At initialization a `Pulsar` object gives itself the default pulse profile (intensity).  If `SignalType` is `'voltage'`, the profile is square rooted to convert from power to amplitude.

https://github.com/PsrSigSim/VersionZeroPointZero/blob/623d4e0d93735db6dd4c95d7fcaf36ea8565b050/pulsar.py#L50-L54

However, if a user calls `gauss_template()` after initialization, there will be no unit conversion even if `SignalType` is `'voltage'`.

## secondary issue
In the snippet above the profile is scaled by the square-root of the profile max.  The max is set to 1 in `guass_template()` already.  This is only necessary for user specified templates, which don't pass through this code anyway.

### PR DESCRIPTION
**Pull request by paulthebaker**
Fixes #25 as described therein.

### CODE REVIEW

**Comment by Hazboun6** [comment]
@paulthebaker , I see the reason for the correction, since the profiles are already normalized to have a maximum of one, but why did you put it in a separate `if` statement? Also, why did you delete the comment? 

FYI, when we are really thinking about two polarization we'll have to let people give two polarization profiles, or at the least dictate how much of the power is in each channel...

**Comment by Hazboun6** [comment]
Ha, never mind, I see the issue now. The fact that 100 lines of code was hidden made it look like you had literally moved the call down 5 lines.  

Great catch. It's really nice to have someone else looking at this code!

Still, why delete the comment?

**Comment by paulthebaker** [comment]
Which comment did I delete?

**Comment by paulthebaker** [comment]
Are `user_template()` generated profiles normalized to max=1?  That fix should be part of this PR, if it's not the case.

**Pull request merged**
