### PR TITLE
pythonize PSS_utils

### PR DESCRIPTION
**Pull request by paulthebaker**
Rewrite `PSS_utils.py` routines with vectorization and readability in mind.  In progress.

### CODE REVIEW

**Comment by paulthebaker** [comment]
None of these routines have been tested with a full work flow.  I've verified consistency with old routines using `numpy.allclose()` for the same input arrays.

These should still be checked with an end-to-end simulation for consistency.  @Hazboun6 do you have an example notebook I could use to do this?

**Comment by Hazboun6** [comment]
@paulthebaker, what type of end-to-end simulation are you thinking about specifically. We are still working on the PSRFITS output. There is a notebook on the notebook server in the shared/simulator folder that uses the NANOGrav templates to simulate some pulses.

**Comment by paulthebaker** [comment]
I'm tempted to rename `top_hat_width()` to `dispersion_dt()` since the width is the dispersion dt across the subband.  this would tie the function to the physics and possibly make it more obvious that it's generally useful for calculating dispersion times.

This function relies on a `df<<f0` limit.  It may also be more common to see `dt(f1, f2)` instead of `dt(df, f0)`.  We could provide both methods, or use kwargs and let the user choose.

Any thoughts on this?

**Comment by paulthebaker** [comment]
Function `PSS_utils.block_mean()` isn't used anywhere in the code.  Is it safe to remove this?

**Comment by Hazboun6** [comment]
It is safe to remove the `block_mean()`. I implemented it for some scintillation calculations, but didn't need it.

**Comment by Hazboun6** [comment]
I think you're correct. It would be good to change the name of `top_hat_width()`. I have an REU implementing the DM broadening in a more structured way right now, and she is almost done with her project. Maybe it would be best if we (read, I) change it after she's done with the project to avoid merge conflicts and general confusion?

**Comment by paulthebaker** [comment]
Re: `text_search()` question: Why do we need to open file twice?

`readlines()` leaves the read cursor at the end of the file, you need to manually move it back to the start (with `seek()`) or close and reopen the file.  It's more efficient to hold the whole file in memory and operate on that array (the function reads in the whole thing anyways), rather than read the file from the i/o buffer twice.

That's what I did in commit 48e1575.

**Comment by paulthebaker** [comment]
@Hazboun6 what's the deal with the commented out functions `DM_broaden_signal()` and `debug_print()`?

Can those be deleted or modified and reinstated?

It also looks like `savitzky_golan()` is also unused.  Can that be removed?

**Comment by paulthebaker** [comment]
Now I've started looking at all of the functions in `PSS_utils`... summary of findings:

### Needs action:
 * `shiftit()` -- redefined (duplicate code) as an `ISM` method.  Should this be moved there completely?  or the `ISM` method could call the function from `PSS_utils`, leaving the general function still available.
 * `top_hat_width()` -- used only once in `ISM.disperse()`, could be moved to `ism.py`.  This is a more general function than advertised.  Above I suggest rename and leave where it is for future uses.
 * `DM_broaden_signal()` -- commented out, unused. Delete?
 * `savitzky_golay()` -- unused. Delete?
 * `find_nearest()` --  used in `PSS_plot.py`, but possibly generally useful.  Is this the only foreseen use?  Can it just be moved there?
 * `acf2d()` -- same situation as `find_nearest()`...
 * `text_search()` -- only used in `ISM.NG_scint_param()`.  Can it be moved there?  I can see this as one of a few file manipulation utilities, *e.g.* dealing with `.par` files.  Probably okay where it is
 * `debug_print()` -- commented out, unused.  Delete?

### Looks good:
 * `down_sample()` -- used in `Telescope.observe()`, TODO'ed in some `Pulsar` methods
 * `rebin()` -- used in several places

**Comment by Hazboun6** [comment]
My general philosophy (which seems to be inline with yours) is to put methods into `PSS_utils.py` that I think will be used in more than one place, either now or eventually. So my opinions are:

- `top_hat_width()` probably will only be used to disperse, so should probably go to `ism.py`

- `DM_Broaden_signal()` can go away. We are about to do a pull request with the new function(s) which live in `ism.py`

 - `savitzky_golay()` I use this, for various reasons when checking signals. It's maybe more for development. It's just a running average, but useful. I usually call it from a notebook. 

 * `shiftit()` Basically I started `PSS_utils.py` with this function when I realized we might use it some where else. This is the function Michael wrote to dedisperse signal in `PyPulse` so it could be used to dedisperse if someone wanted to. I'm not sure whether to leave it or get rid of it for the one in `ism.py`. 

The following three seem like they might/will be used multiple times in the future, but as you note, are currently only used once. I'd vote that they stay.
 * `find_nearest()` --  used in `PSS_plot.py`, but possibly generally useful.  Is this the only foreseen use?  Can it just be moved there?
 * `acf2d()` -- same situation as `find_nearest()`...
 * `text_search()` -- only used in `ISM.NG_scint_param()`.  Can it be moved there?  I can see this as one of a few file manipulation utilities, *e.g.* dealing with `.par` files.  Probably okay where it is

I meant to write a debugging script that could be turned on and off with a flag, but never did. Feel free to delete. I can write it later if I need it again. 
 * `debug_print()` -- commented out, unused.  Delete?

I agree with these assessments. 
### Looks good:
 * `down_sample()` -- used in `Telescope.observe()`, TODO'ed in some `Pulsar` methods
 * `rebin()` -- used in several places

**Comment by Hazboun6** [comment]
As for `text_search()` you see that I wrote it as a general function, and then tweaked it to use for the specific text file I needed to read. As noted in the comments, I could not make the darn thing work without opening it twice. I spent too much time trying to get it to be pretty, so I settled for working code. 

That was my first foray into the file i/o commands, so I'm very glad for the explanation! Have you tested that it works in your rewrite? If so then great! Let's definitely use your more efficient way.

**Comment by Hazboun6** [comment]
Have you tested the `shift_it()` code to see if it's substantially faster vectorized? If so then Michael might be very interested in that.

**Review by Hazboun6 — APPROVED** [review]
All of these changes look great! As long as the `shiftit()` code works the same, then I think we should be set to merge.

**Comment by paulthebaker** [comment]
I tested everything in a local notebook as individual functions, but not as part of a larger simulation.  For `text_search()`, I didn't have an example of the file you use.  I tested some stuff on a random file, but it should be tested with a file in the actual format.

**Pull request merged**
