### PR TITLE
Setup.py Addition

### PR DESCRIPTION
**Pull request by bshapiroalbert**
Added `pdat` to the requirements in setup.py

### CODE REVIEW

**Comment by Hazboun6** [comment]
Well in hindsight it was already getting to `fitsio` anyways so `tox` must install from the `requirement.txt` which already had `pdat`. I google for a second, but this seems like a deeper issue. Like maybe cython compiled packages having issues finding `numpy.core`? Not sure. And unfortunately my next couple of days are packed.

**Comment by Hazboun6** [comment]
The [fitsio `.travis.yml`](https://github.com/esheldon/fitsio/blob/master/.travis.yml) might be useful? Also Erin Sheldon has been very responsive to me in the past. Looks like they are demanding `numpy==1.11` for some reason?

**Comment by bshapiroalbert** [comment]
I did a little bit of googling and it looks like it might have to do with having an older version of `numpy`. The requirements.txt file currently requires `numpy==1.13.3`, so that's what gets imported for the test, but is there a specific reason that that's required? Most the issues I've seen that have this same error have to do with importing `tensorflow` and the solution seems to be a newer version of `numpy`, maybe 1.16.4 or something (that's what's suggested and also the version I have on my local machine)?

**Comment by Hazboun6** [comment]
You can just change `==` to `>=`. Also feel free to change the number. The template `requirements.txt` always sets things to `==` for some reason...

**Pull request merged**
