### PR TITLE
update Telescope class

### PR DESCRIPTION
**Pull request by paulthebaker**
Total rewrite of Telescope class as specified in issue #1 .  Currently in progress, still needs: 
 * handle noise with T<sub>sys</sub>
 * initialize empty `Signal()`
 * possible rewrite of `observe()`
 * redo `system` as class
 * other changes as needed...

### CODE REVIEW

**Comment by paulthebaker** [comment]
Syntax to observe with GBT:
```python
import telescope

gbt = telescope.GBT()
out = gbt.observe(mySignal, system='Lband_GUPPI')
```

`mySignal` is a `Signal()` object, `out` is an array.

**Question:** should `out` be a new `Signal()` object?

**Comment by Hazboun6** [comment]
This looks great @paulthebaker ! Thanks for the rewrite. Do you think that we should be using class factories for the telescopes? In some sense that is basically what you are doing, but is there a cleaner way? 

Can you give me your 2 cents as to why we should declare variables as properties? 

I fixed one small bug, which referred to `self.Nt`, but the value lives in the signal object which is an input, so I refer to it as `signal.Nt`. 

As for your last question I think it will matter whether we are in 'explore' mode or 'simulate' mode, and whether we want to give the user the option to keep both signals. There is so much information carried around within a signal class that a user might want to know, though in the end I think many users will just output a PSRFITS file and be done with it. I think that what we should probably do at this stage is actually just add the `out` array to the `signal` class as a new array. Probably with an option to overwrite the old `signal` array if they want to be economical with memory.

**Review by Hazboun6 — APPROVED** [review]
This looks great. I think we should probably add the `out` array to the incoming signal class. Probably put in some options for the old signal to be over written or keep both.

**Comment by paulthebaker** [comment]
Using `@property` lets us declare attributes as private.  Anything prepended with an underscore is private to the object, to discourage the user from messing with it.  For instance, private methods/attributes aren't listed in `jupyter` autocomplete suggestions.
 * `Telescope.name` is actually a method that returns the private attribute `_name`
 * declaring it with the `@property` decorator makes it work without the usual `()` so it looks like an  attribute to the user: `print(Telescope.name)` works as expected
 * if the user tries to rename the telescope: `Telescope.name = 'Jimmy'`, it will throw an error.
 * this locks in the telescope's attributes at declaration they cannot be changed.
 * well... the user could do `Telescope._name = 'Jimmy'`, but they'd have to know what they're doing

If we want to be able to be able to set the attribute (or fail gracefully if someone tries to set it) we can add a setter method later using the `@name.setter` decorator.

Object oriented folk call this 'encapsulation'.

**Comment by paulthebaker** [comment]
I set the bandwidth of the AO and GBT receivers / backends arbitrarily.  We need to check those!

**Comment by paulthebaker** [comment]
@Hazboun6, common radio equations are often quoted dimensionfully, (*e.g.* f in MHz gives S in mJy).  Should I convert everything to Hz, sec, Jy, etc, then convert output as needed, or put inputs into equations with units as specified in textbooks?

**Comment by paulthebaker** [comment]
I committed the updates, but I'm still trying to figure out how to convert to the `int` counts.  I need to map the mean flux density to the profile max.

I'm a bit confused how you calibrate the pulse amplitude to the `int` counts scale.

**Comment by Hazboun6** [comment]
Hi Paul,
It might be too late to answer your first question, but the standard
throughout the code has been to put a reference to a specific equation
number, where possible, and use the units in that reference (of course also
including some documentation directly in the code as to what units we use.)
I see more and more how it would be really handy to start using astropy to
take care of all of that for us, but that is going to have to be a topic
for another day.

**Comment by Hazboun6** [comment]
I'll answer your other question on  the Slack channel, so I can add some code blocks more easily...

**Comment by paulthebaker** [comment]
The idea is:
 * we can calculate the radiometer noise level, `sigS`, in physical units of flux density (mJy) given the system temperature
 * the pulse profile is mapped from arbitrary units (0-1) to machine counts (0-127) by setting the profile peak to a given `int` value
 * if we know the profile peak in physical units we can use this to determine the mapping from mJy to machine counts

We determine the profile peak, `Smax`, in physical units, from the mean flux density per period, `Smean`, by:

```python
Smax = Smean / (sum(pr) * dph)
```
where `pr` is the profile array in (0-1) units and `dph` is the phase bin size of the profile.

For (0-1) units 1 -> `Smax` and 1 -> `xxx_draw_norm`. So the conversion from mJy to machine counts for this signal is

```python
mJy2cnt = xxx_draw_norm / Smax
sigInt = sigS * mJy2cnt
```

## Note
The above only works for intensity (filterbank) data.  For voltage (baseband) data the profile is an amplitude not power!  I **think** (?) everything should work out if we simple work with the `sqrt` of all of the intensity parameters:

```python
Amax = np.sqrt(Smean) / (sum(pr) * dph)  # profile is already amp (not pow)
V2cnt = xxx_draw_norm / Amax
sigInt = np.sqrt(sigS) * V2cnt
```

@Hazboun6, do you follow this?  Does this sound correct?  `Smax` should be computed once and added to the `PulsarDict`.  This could be its own pulsar method that is called during profile generation.

**Pull request merged**
