### PR TITLE
Added more tests for profile and portrait classes

### PR DESCRIPTION
**Pull request by bshapiroalbert**
Added more tests for the profile and portrait classes, particularly for the non-DataProfile/Portrait classes. Coverage is improved but some lines are untestable due to how certain lines are set up. In addition, a number of bugs were fixed, and some comments added when certain lines were not testable.

### CODE REVIEW

**Comment by Hazboun6** [comment]
Hi @bshapiroalbert this looks great. Thanks for adding these. Is there a way to more deeply fix the `init_profile` calls? Like should we make that method in the base class run a `NotImplemented` error, and only add it in the profiles/portrait classes where it would be used? I know that @paulthebaker added that method as a convenience for particular uses. @bshapiroalbert do you use it in your current workflow?

**Comment by bshapiroalbert** [comment]
Hey @Hazboun6, I think the best way would be to make it have a `NotImplemented` error as you mentioned. The  `GaussPortrait` has it's own version defined anyways. The `DataPortrait` would need it though because that's what the `pulsar` class calls under the hood when you run `make_pulses` I don't call it explicitly in my current workflow I don't think, but the `pulsar` class does. Although, maybe because it does that that function does get called and tested somewhere else in the pipeline, I was just trying to have the specific tests in their specific places. Maybe I need to run the full coverage tests to see what the missing lines are.

**Comment by bshapiroalbert** [comment]
I just ran the coverage and checked the missing lines and it looks like they do get tested and used somewhere in the tests actually, so I think things are okay, I should go remove those comments.

**Comment by Hazboun6** [comment]
Great, should we delete those comments then before accepting the PR?

**Comment by bshapiroalbert** [comment]
Yeah I can do that shortly.

**Comment by bshapiroalbert** [comment]
Comments have been removed. Ready to merge now I think.

**Pull request merged**
