### PR TITLE
Astropy Quantity Method

### PR DESCRIPTION
**Pull request by Hazboun6**
Added a method `make_quant()` in `PSS_util` that checks to see if an input is an astropy quantity, and if it is not, makes it into one with default units. Bases on @paulthebaker 's  #13 .

Can be used as follows:
```python
self.f0 = make_quant(f0,'MHz')
```
Returns astropy quantity with units of MHz.

### CODE REVIEW

**Comment by Hazboun6** [comment]
My current plan is to merge changes once Travis CI checks out...

**Comment by paulthebaker** [comment]
This just adds the `make_quant` and `unit_init` functions.  It doesn't use them anywhere, yet?

**Comment by paulthebaker** [comment]
you'll have to add `astropy` to the requirements, so travis installs it before running...

While you're doing that can you change the `scipy` and `matplotlib` reqs to be `>=`.  `numpy` needs to stay fixed at `1.13.3` for the time being.  I'm not sure about `h5py`.

**Comment by Hazboun6** [comment]
And correct the functions are there, but not used in the code yet.

**Review by paulthebaker — APPROVED** [review]
This looks good. We'll need to normalize all of our docstrings eventually... and have tests for everything.

**Pull request merged**
