### PR TITLE
Fixed sampling rate bug when creating a signal from a fitsfile

### PR DESCRIPTION
**Pull request by bshapiroalbert**
Fixed a sampling rate issue for subintegrated data when initializing a filterbank signal from a fits file. 

I have not written a test for this yet though since it would require hosting a psrfits file somewhere, which I do not have permission to do yet, so may want to wait to merge.

### CODE REVIEW

**Comment by Hazboun6** [comment]
What "permission" are you referring to here?

**Comment by bshapiroalbert** [comment]
Sorry that was unclear. If we wanted to use a NANOGrav fits file as a template we should get permission from probably the management team, even if we replace the data in it with zeros or something, since it would become a public file, even just for testing.

**Comment by Hazboun6** [comment]
I believe all of our data is public at some point, though @mtlam would know better.

**Comment by bshapiroalbert** [comment]
I know that the par and tim files are, I wasn't sure if the raw data files became public as well.

**Comment by mtlam** [comment]
The templates are in the data release tarballs so those should be fair game.

**Pull request merged**
